spring.application.name=marketplace
spring.mongodb.uri=mongodb+srv://holodnikovmaio51mp_db_user:THgT1BdqYH8By7yu@cluster0.9t6ngjg.mongodb.net/marketplace?retryWrites=true&w=majority&appName=Cluster0
server.port=8082